// 1. general API stuff
export const API_OK = 'API_OK';
export const API_NO = 'API_NO';

// 2. global loading flag
export const LOADING_TRUE = 'LOADING_TRUE';
export const LOADING_FALSE = 'LOADING_FALSE';

// 3. load token
export const TOKEN_USE = 'TOKEN_USE';

export const YT_CATEGORIES_QUERIED = 'YT_CATEGORIES_QUERIED';
export const YT_CATEGORIES_RECEIVED_OK = 'YT_CATEGORIES_RECEIVED_OK';
export const YT_CATEGORIES_RECEIVED_NO = 'YT_CATEGORIES_RECEIVED_NO';

export const YT_SEARCH_QUERIED = 'YT_SEARCH_QUERIED';
export const YT_SEARCH_RECEIVED_OK = 'YT_SEARCH_RECEIVED_OK';
export const YT_SEARCH_RECEIVED_NO = 'YT_SEARCH_RECEIVED_NO';

export const YT_SEARCH_CATEGORY_QUERIED = 'YT_SEARCH_CATEGORY_QUERIED';
export const YT_SEARCH_CATEGORY_RECEIVED_OK = 'YT_SEARCH_CATEGORY_RECEIVED_OK';
export const YT_SEARCH_CATEGORY_RECEIVED_NO = 'YT_SEARCH_CATEGORY_RECEIVED_NO';

export const YT_SEARCH_RELATED_QUERIED = 'YT_SEARCH_RELATED_QUERIED';
export const YT_SEARCH_RELATED_RECEIVED_OK = 'YT_SEARCH_RELATED_RECEIVED_OK';
export const YT_SEARCH_RELATED_RECEIVED_NO = 'YT_SEARCH_RELATED_RECEIVED_NO';

export const YT_SEARCH_LAZY_LOAD_QUERIED = 'YT_SEARCH_LAZY_LOAD_QUERIED';
export const YT_SEARCH_LAZY_LOAD_RECEIVED_OK = 'YT_SEARCH_LAZY_LOAD_RECEIVED_OK';
export const YT_SEARCH_LAZY_LOAD_RECEIVED_NO = 'YT_SEARCH_LAZY_LOAD_RECEIVED_NO';
